[env]
platform      = espressif32
framework     = arduino

monitor_speed = 115200
upload_speed  = 921600

; Serieller Monitor: ESP32 Exception Decoder für bessere Crash-Ausgaben
monitor_filters = esp32_exception_decoder

build_flags = -I include

lib_deps =
    fastled/FastLED @ ^3.9.0
    bblanchon/ArduinoJson @ ^7.0

[env:esp32-s3-devkitc-1]
board        = esp32-s3-devkitc-1
upload_port  = /dev/tty.usbmodem14301
monitor_port = /dev/tty.usbmodem14301

build_flags =
    ${env.build_flags}
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

board_build.flash_mode = qio

[env:az-delivery-devkit-v4]
board        = az-delivery-devkit-v4
upload_port  = /dev/cu.SLAB_USBtoUART
monitor_port = /dev/cu.SLAB_USBtoUART
